name: kstream
description: Simple rtmp streamer

version: 0.0.1+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  permission_handler: ^8.3.0
  shared_preferences: ^2.0.6
  unicons: ^2.0.1
  package_info: ^2.0.2
  uuid: ^3.0.6

#  flutter_rtmp_streamer:
#    path: ../flutter_rtmp_streamer/


  flutter_rtmp_streamer:
    git:
      url: https://github.com/kuzalex2/flutter_rtmp_streamer.git
      ref: 6374be9e210d20143ceccc11e71c8636c1e7b114

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.1

flutter:

  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic